### ISSUE TITLE
Change Player.enchant example

### ISSUE THREAD

**Issue by ghost** [Connor4898/ModPE-Docs#4]
Replace Player.getSelectedSlot() with Player.getSelectedSlotId()

**Comment by slice** [comment]
Are you sure? Your suggestion doesn't seem correct.

**Comment by zhuowei** [comment]
@s3r1alpari4h Whoops, good catch: (https://github.com/zhuowei/ModPEScripts/blob/master/500ise_exttest.js#L261) Will fix soon.

Edit: fixed.

**Comment by slice** [comment]
Wait, does `getSelectedSlotId()` return the slot ID or the item ID of the item in the slot? I'm kinda confused.

**Comment by ghost** [comment]
It returns the selected slot ID.

**Comment by slice** [comment]
@s3r1alpari4h Ah, okay.
